version: '3.3'

networks:
  proxy:
    external: true

services:
  nginx:
    image: tbartifactory-artifactory01.prod.247media.com:5003/nginx:1.13
    networks:
    - proxy
    deploy:
      replicas: 2
      labels:
      - traefik.frontend.rule=PathPrefixStrip:/nginx
      - traefik.docker.network=proxy
      - traefik.port=80
      - traefik.enable=true
  apache:
    image: tbartifactory-artifactory01.prod.247media.com:5003/httpd:2.4
    networks:
    - proxy
    deploy:
      replicas: 2
      labels:
      - traefik.frontend.rule=PathPrefixStrip:/apache
      - traefik.docker.network=proxy
      - traefik.port=80
      - traefik.enable=true
  caddy:
    image: tbartifactory-artifactory01.prod.247media.com:5003/abiosoft/caddy:0.10.7
    networks:
    - proxy
    deploy:
      replicas: 2
      labels:
      - traefik.frontend.rule=PathPrefixStrip:/caddy
      - traefik.docker.network=proxy
      - traefik.port=2015
      - traefik.enable=true
  apiv1:
    image: tbartifactory-artifactory01.prod.247media.com:5003/z0r1k/whoami
    networks:
    - proxy
    environment:
      - serviceName=apiv1
    deploy:
      replicas: 2
      labels:
      - traefik.frontend.rule=PathPrefixStrip:/api/v1
      - traefik.frontend.priority=10
      - traefik.docker.network=proxy
      - traefik.port=80
      - traefik.enable=true
  apiv2:
    image: tbartifactory-artifactory01.prod.247media.com:5003/z0r1k/whoami
    networks:
    - proxy
    environment:
      - serviceName=apiv2
    deploy:
      replicas: 2
      labels:
      - "traefik.frontend.rule=PathPrefixStrip:/api/v2,/api"
      - traefik.frontend.priority=1
      - traefik.docker.network=proxy
      - traefik.port=80
      - traefik.enable=true
